apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-secure-microservice.fullname" . }}
  labels:
    {{- include "sample-secure-microservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
  selector:
    {{- include "sample-secure-microservice.selectorLabels" . | nindent 4 }}
